const arrayCards = [
  {
    number: 1,
    subTitle: 'SABIA',
    backgroundColor: '#C5677F',
    color: '#E7B6C2',
    svgName: 'sabia',
    text: `"Tanto para falar, tão pouco tempo para apresentar"`,
  },
  {
    number: 2,
    subTitle: 'CARA COMUM',
    backgroundColor: '#0B2C4B',
    color: '#A8CBEB',
    svgName: 'comum',
    text: `"A palestra é uma simples conversa"`,
  },
  {
    number: 3,
    subTitle: 'CRIATIVO',
    backgroundColor: '#D4801D',
    color: '#FFD39E',
    svgName: 'criativo',
    text: `"Minha cabeça está fervendo com tantas ideias para a palestra"`,
  },
  {
    number: 4,
    subTitle: 'FORA DA LEI',
    backgroundColor: '#071434',
    color: '#92A8E0',
    svgName: 'fora_da_lei',
    text: `"Não tem uma regra sobre como fazer uma palestra"`,
  },
  {
    number: 5,
    subTitle: 'INOCENTE',
    backgroundColor: '#A071B9',
    color: '#DDC4EA',
    svgName: 'inocente',
    text: `"Sou feliz no palco"`,
  },
  {
    number: 6,
    subTitle: 'HERÓI',
    backgroundColor: '#D7AA13',
    color: '#DCC9AB',
    svgName: 'heroi',
    text: `"Vamos subir ao palco, nós trilhamos um longo caminho até aqui"`,
  },
  {
    number: 7,
    subTitle: 'GOVERNANTE',
    backgroundColor: '#6B3916',
    color: '#E1B99D',
    svgName: 'governante',
    text: `"Tudo pronto para a melhor palestra que já fiz"`,
  },
  {
    number: 8,
    subTitle: 'MÁGICO',
    backgroundColor: '#3BDF80',
    color: '#DBFFEA',
    svgName: 'magico',
    text: `"Vocês não imaginam o que preparei para esta palestra"`,
  },
  {
    number: 9,
    subTitle: 'PRESTATIVO',
    backgroundColor: '#843C23',
    color: '#E3A48E',
    svgName: 'prestativo',
    text: `"Espero que minhas palavras te ajuidem"`,
  },
  {
    number: 10,
    subTitle: 'EXPLORADOR',
    backgroundColor: '#3CA65C',
    color: '#A0DAB1',
    svgName: 'explorador',
    text: `"Falar para vários mundos e levar o mundo para todos"`,
  },
  {
    number: 11,
    subTitle: 'BOOBO DA CORTE',
    backgroundColor: '#C70077',
    color: '#DAADC8',
    svgName: 'bobo_da_corte',
    text: `"Eu percoo o público, mas não perco a piada"`,
  },
  {
    number: 12,
    subTitle: 'AMANTE',
    backgroundColor: '#BD0162',
    color: '#EDBBD5',
    svgName: 'amante',
    text: `"Gosto de plateia cheia"`,
  }
]

export default arrayCards
